# Generated by Django 3.1.4 on 2020-12-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='redirect',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
