# Generated by Django 3.1.4 on 2020-12-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertracker', '0002_monitor_redirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
