# Generated by Django 3.1.4 on 2020-12-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertracker', '0004_monitor_full_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='is_url',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monitor',
            name='redirect',
            field=models.CharField(max_length=50),
        ),
    ]
