# Generated by Django 3.1.4 on 2020-12-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertracker', '0006_auto_20201224_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='is_url',
        ),
        migrations.AddField(
            model_name='monitor',
            name='time',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
    ]
