# Generated by Django 3.1.4 on 2020-12-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertracker', '0007_auto_20201224_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='ip',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
