# Generated by Django 3.1.4 on 2020-12-24 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usertracker', '0008_auto_20201224_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='time',
        ),
    ]
