# Generated by Django 3.1.4 on 2020-12-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertracker', '0009_remove_monitor_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
