# Generated by Django 3.1.4 on 2020-12-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertracker', '0010_monitor_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
